# Hoş Geldiniz {.unnumbered}

Bu web sitesi, **"Veri Bilimi için R"** kitabının 2. baskısının Türkçe çevirisidir.
Bu kitap, veri bilimi becerileri için bir **uygulama klavuzu** niteliğindedir. 
Nasıl ki bir kimyager işe deney tüplerini temizlemeyi ve laboratuvar düzenini sağlamayı öğrenerek başlıyorsa, siz de veriyi temizlemeyi, grafikler üzerinden hikaye anlatmayı ve daha pek çok kritik yetkinliği burada öğreneceksiniz. 
Bunlar, veri bilimini "teori" olmaktan çıkarıp "eyleme" dönüştüren becerilerdir. Burada, tüm bu süreçleri R ile yürütürken kullanılan en güncel **sektörel standartları** (best practices) bulacaksınız.
Zamanı verimli kullanmak adına; **grafik grameri** (grammar of graphics), **açıklamalı programlama** (literate programming) ve **tekrarlanabilir araştırma** yöntemlerini nasıl kullanacağınızı göreceksiniz. 
Ayrıca; veri düzenleme (wrangling), görselleştirme ve keşif dolu analiz süreçlerinde, zihinsel enerjinizi yeni bulgulara odaklayabilmek için bilişsel kaynaklarınızı nasıl yönetmeniz gerektiğini öğreneceksiniz.

Bu web sitesi her zaman ücretsiz kalacaktır ve [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) lisansı ile korunmaktadır.
Kitabın fiziksel bir kopyasına sahip olmak isterseniz [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20).üzerinden sipariş verebilirsiniz. 
Eğer kitabın ücretsiz sunulmasını değerli buluyor ve bu emeğe karşılık vermek istiyorsanız, lütfen [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): vakfına bağışta bulunun: 
R4DS'in kapağında da yer alan [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) Yeni Zelanda'ya özgü, nesli kritik derecede tehlike altında olan bir papağan türüdür; dünyada sadece 244 adet kalmıştır.

Başka bir dil konuşuyorsanız, kitabın birinci baskısının ücretsiz olarak sunulan şu çevirileri ilginizi çekebilir:

-   [Spanish](http://es.r4ds.hadley.nz)
-   [Italian](https://it.r4ds.hadley.nz)
-   [Turkish](https://tr.r4ds.hadley.nz)
-   [Portuguese](https://pt.r4ds.hadley.nz)

ve ikinci baskısı:

-   [Spanish](https://davidrsch.github.io/r4ds-es/)

Kitaptaki alıştırmalar için önerilen çözümlere <https://mine-cetinkaya-rundel.github.io/r4ds-solutions> adresinden ulaşabilirsiniz.

Lütfen unutmayın; R4DS, bir [Katılımcı Davranış Kuralları](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html) (Contributor Code of Conduct) protokolü uygulamaktadır. 
Bu kitaba katkıda bulunarak, ilgili protokolün şartlarına uymayı kabul etmiş sayılırsınız.

---

# Çeviriye Önsöz {.unnumbered}

21. yüzyılda hızlanarak devam eden bilgi devrimi, insan hayatının her alanından toplanan veri miktarını üssel bir şekilde artırmış; 
veriye erişimin demokratikleşmesi ise modern dünyanın en önemli kazanımlarından biri haline gelmiştir. 
Sosyal bilimlerden temel bilimlere, tıptan mühendisliğe kadar her alanda veri toplamak ve analiz etmek, geçmişte yalnızca kısıtlı bir kesimin tekelindeydi. 
Bugün ise “büyük veri” setlerinin erişilebilir olması, bilimle uğraşmak isteyen herkes için büyük bir "eşitleyici" rol üstlenmektedir.
Veri bilimi (data science), işte bu özgürleştirici atmosferde tüm disiplinlerle iç içe geçen hayati bir meslek grubu olarak doğmuştur.

Günümüz veri analisti için bir diğer büyük eşitleyici unsur ise R gibi ücretsiz, açık kaynaklı ve topluluk destekli programlama dillerinin yaygınlaşmasıdır. 
Artık karmaşık analizler gerçekleştirmek isteyen bir araştırmacının tek ihtiyacı bir bilgisayar, internet bağlantısı ve doğru rehberlere ulaşma isteğidir.

### Bir Geleneğin Devamı: 2. Baskı (2e)
