# Transform {#sec-transform-intro .unnumbered}

```{r}
#| label: setup
#| file: "_common.R"
#| include: false
```

In this part of the book, you'll learn about various types of data the columns of a data frame can contain and how to transform them.
The transformations you might want to apply to a column vary depending on the type of data you're working with, for example if you have text strings you might want to extract or remove certain pieces while if you have numerical data, you might want to rescale them.
You've already learned a little about data wrangling in the previous part.
Now we'll focus on new skills for specific types of data you will frequently encounter in practice.

<!--# TO DO: Add a diagram? -->

This part of the book proceeds as follows:

-   In Chapter \@ref(tibbles), you'll learn about the variant of the data frame that we use in this book: the **tibble**.
    You'll learn what makes them different from regular data frames, and how you can construct them "by hand".

-   Chapter \@ref(relational-data) will give you tools for working with multiple interrelated datasets.

-   Chapter \@ref(numbers) ...

-   Chapter \@ref(logicals) ...

-   Chapter \@ref(missing-values)...

-   Chapter \@ref(strings) will give you tools for working with strings and introduce regular expressions, a powerful tool for manipulating strings.

-   Chapter \@ref(regular-expressions) ...

-   Chapter \@ref(factors) will introduce factors -- how R stores categorical data.
    They are used when a variable has a fixed set of possible values, or when you want to use a non-alphabetical ordering of a string.

-   Chapter \@ref(dates-and-times) will give you the key tools for working with dates and date-times.

-   Chapter \@ref(column-wise) will give you tools for performing the same operation on multiple columns.

<!-- TO DO: Add chapter descriptions -->
